config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles, only: [:show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  enum status: %i(draft limiting publish)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order(created_at: :desc)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path, notice: '保存しました'
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @html = markdown.render(@article.text)
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

    def article_params
      params.require(:article).permit(:title, :text)
    end

    def set_article
      @article = Article.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1 class="headingtype-1 headingtype-green">markdown sample</h1>
<%= link_to '新規作成', new_article_path %>

<% @articles.each do |article| %>
  <div class="memos">
    <%= link_to article.title, article_path(article) %>
    <%= link_to '削除', article_path(article), class: 'delete-btn', method: :delete %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1 class="headingtype-1 headingtype-green">Markdown Editor</h1>
<%= form_for @article, html: { class: 'editor-box row' } do |f| %>
  <div class="col-xs-6 editor">
    <%= f.text_field :title, id: 'title', autofocus: true, placeholder: 'タイトルを入力してください' %>
    <%= f.text_area :text, id: 'editor', class: 'form-control', placeholder: 'Markdown記法で入力してね' %>
  </div>
  <div class="col-xs-6">
    <div class="result">
      <h1 id="title-result" class="preview"></h1>
      <div id="result" class="preview">
      </div>
    </div>
  </div>
  <div class="col-xs-12 actions">
    <%= button_to 'CANCEL', root_path, class: 'btn btn-default' %>
<!-- todo:復数のサブミットボタンを用意し、限定公開、下書きを追加する -->
    <%= f.submit "SUBMIT", class: 'btn btn-submit' %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1 class="headingtype-1 headingtype-green"><%= @article.title %></h1>
<div class="row memo-content" id="memo-text">
  <%= @html.html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkdownSampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>